# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "one"
  dev:
    runs-on: windows-latest
    steps:
      - run: echo "two"
  five:
    runs-on: ubuntu-latest
    needs: [test, dev]
    if: always()
    steps:
      - run: echo "How to know the status of execution of jobs.one and jobs.two?"
