# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Multiple Jobs in Single Workflow

on:
  push:
    branches: [ main ]
 
jobs:
  one:
    runs-on: self-hosted

    steps:
    
    #Checkout the code
    - name: Checkout the code
      uses: actions/checkout@v2
      
    #Copy to Local
    - name: Copy to local      
      run: scp -o  StrictHostKeyChecking=no -i C:\Users\trbor\Downloads\POC_AWS.pem ${{ secrets.USER }}@${{ secrets.HOST }}:/home/ec2-user/GitHub_Actions/SubmissionDataForm-0.0.1-SNAPSHOT.jar D:\Actions\
   
   
  two:
   runs-on: ubuntu-latest
   
   steps:
   #Checkout the code
   - name: Checkout the code
     uses: actions/checkout@v2
   
   - name: Build with maven
     run: 
          mvn clean;
          mvn install;
  #Velify the all the folders in Main Directory     
   - name: Operations
     uses: fifsky/ssh-action@master
     with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          command: 
                  sudo su;
                  ls -a;
            
  #Copy via SCP to remote repository ec2           
   - name: copy file via ssh password
     uses: noobly314/deploy-with-scp@v1
     with:
        server-ip: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USER }}
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        src: "/home/runner/work/SSH_SCP/SSH_SCP/target/SubmissionDataForm-0.0.1-SNAPSHOT.jar"
        dest: "/home/ec2-user/GitHub_Actions/"
        
  three:
   runs-on: ubuntu-latest
   
   needs: [one, two]
   if: always()
   steps:
      - run: echo "How to know the status of execution of jobs.one and jobs.two?"
     
     
     
     
     
     
     
     
